apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "geoanalyzer.fullname" . }}-frontend
  labels:
    {{- include "geoanalyzer.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "geoanalyzer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "geoanalyzer.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "geoanalyzer.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-frontend
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.imageFrontend.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.imageFrontend.pullPolicy }}
          ports:
            - name: http-frontend
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http-frontend
          readinessProbe:
            httpGet:
              path: /
              port: http-frontend
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "geoanalyzer.fullname" . }}-backend
  labels:
    {{- include "geoanalyzer.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "geoanalyzer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "geoanalyzer.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "geoanalyzer.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-backend
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.imageBackend.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.imageBackend.pullPolicy }}
          env:
            - name: TRACCAR_URL
              value: {{ .Values.traccar.url }}
          ports:
            - name: http-backend
              containerPort: 5000
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
