{{- if .Values.ingress.enabled -}}
{{- $fullName := include "geoanalyzer.fullname" . -}}
{{- $portBackend := .Values.service.portBackend -}}
{{- $portFrontend := .Values.service.portFrontend -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "geoanalyzer.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
    nginx.ingress.kubernetes.io/use-regex: "true"
  {{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.ingress.hostname | quote }}
      secretName: {{ .Values.ingress.secretName }}
{{- end }}
  rules:
    - host: {{ .Values.ingress.hostname | quote }}
      http:
        paths:
          - path: /api/
            backend:
              serviceName: {{ $fullName }}-backend
              servicePort: {{ $portBackend }}
          - path: /
            backend:
              serviceName: {{ $fullName }}-frontend
              servicePort: {{ $portFrontend }}
{{- end }}
